services:
  discovery-service:
    container_name: discovery-service
    build: ./Discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "http://192.168.189.159:8761/actuator/health"]
      interval: 10s
      retries: 4

  config-service:
    container_name: config-service
    build: ./Config_Service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: ["CMD", "curl", "http://192.168.189.159:9999/actuator/health"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.189.159:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy

  chercheur-service:
    build: ./Chercheur-Service
    container_name: chercheur-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: ["CMD", "curl", "http://192.168.189.159:8082/actuator/health"]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.189.159:8761/eureka
      - CONFIG_SERVICE=http://192.168.189.159:9999
    depends_on:
      config-service:
        condition: service_healthy

  gateway_service:
    build: ./Gateway_Service
    container_name: gateway_service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.189.159:8761/eureka
      - CONFIG_SERVICE=http://192.168.189.159:9999
    healthcheck:
      test: ["CMD", "curl", "http://192.168.189.159:8888/actuator/health"]
      interval: 10s
      retries: 4
    networks:
      default:
        ipv4_address: 192.168.189.159
    depends_on:
      config-service:
        condition: service_healthy
